import type { DashboardSnapshot } from './types'

export const fixtureSnapshot: DashboardSnapshot = {
  source: 'local-fixture',
  tasks: [
    {
      id: 'run-local-001',
      name: '本地五靶场回归 · 第 1 轮',
      kind: 'local-lab',
      state: 'running',
      stage: '受控验证',
      progress: 62,
      elapsedSeconds: 148,
      counters: { endpoints: 42, api: 18, candidates: 4, blocked: 1, errors: 0 },
      networkContact: 'loopback',
      updatedAt: '2026-08-26T23:40:00+08:00',
    },
    {
      id: 'run-offline-004',
      name: '离线审阅 · 示例项目',
      kind: 'offline-review',
      state: 'completed',
      stage: '报告生成',
      progress: 100,
      elapsedSeconds: 89,
      counters: { endpoints: 0, api: 0, candidates: 2, blocked: 0, errors: 0 },
      networkContact: 'none',
      updatedAt: '2026-08-26T22:10:00+08:00',
    },
  ],
  labs: [
    { id: 'juice-shop', name: 'Juice Shop', port: 3000, health: 'healthy', stage: '受控验证', durationSeconds: 39, candidates: 2, reportId: 'report-juice', localOnly: true },
    { id: 'dvwa', name: 'DVWA', port: 8081, health: 'healthy', stage: '候选研判', durationSeconds: 31, candidates: 1, reportId: 'report-dvwa', localOnly: true },
    { id: 'webgoat', name: 'WebGoat', port: 8082, health: 'healthy', stage: '入口发现', durationSeconds: 25, candidates: 0, localOnly: true },
    { id: 'vampi', name: 'VAmPI', port: 8083, health: 'starting', stage: '健康检查', durationSeconds: 12, candidates: 1, localOnly: true },
    { id: 'business-api', name: 'Business API', port: 8084, health: 'healthy', stage: 'API 对象对比', durationSeconds: 41, candidates: 0, reportId: 'report-business-api', localOnly: true },
  ],
  events: [
    { id: 1, taskId: 'run-local-001', time: '23:37:33', level: 'success', stage: '策略检查', message: '仅本地回环模式已启用', tool: 'policy', redacted: true },
    { id: 2, taskId: 'run-local-001', time: '23:37:41', level: 'success', stage: '依赖检查', message: '五个靶场健康端点已登记', tool: 'docker', redacted: true },
    { id: 3, taskId: 'run-local-001', time: '23:38:04', level: 'info', stage: '入口发现', message: '已处理授权夹具中的 42 个入口', tool: 'local-adapter', redacted: true },
    { id: 4, taskId: 'run-local-001', time: '23:38:52', level: 'warning', stage: '受控验证', message: '1 个非破坏性动作被策略阻止', tool: 'scope-guard', redacted: true },
    { id: 5, taskId: 'run-local-001', time: '23:39:41', level: 'info', stage: '候选研判', message: '4 个候选已进入人工复核队列', tool: 'adjudicator', redacted: true },
  ],
  findings: [
    {
      id: 'finding-001',
      title: '反射型输入点需要人工确认',
      severity: 'medium',
      source: 'DVWA · 安全夹具',
      state: '待人工复核',
      summary: '普通文本标记在回环训练页面中被原样反射。该结果只说明存在候选输入点，不等同于可提交漏洞。',
      evidence: '响应摘要：包含 SRC-Auto-Marker-2026；完整响应正文未写入事件日志。',
      prerequisites: ['本地 DVWA 默认训练账号', '允许的 GET 请求', '回环端口 8081'],
      impact: '需要人工判断输出上下文、编码方式和实际影响。',
    },
    {
      id: 'finding-002',
      title: '对象权限差异候选',
      severity: 'low',
      source: 'Business API · 对象矩阵',
      state: '待人工复核',
      summary: '两个合成角色读取对象时出现字段差异，尚未完成越权结论。',
      evidence: '仅保存字段集合指纹和状态码类别，不保存账号、Token 或完整对象内容。',
      prerequisites: ['本地合成角色 A/B', '只读对象接口', '固定对象 ID'],
      impact: '需人工核对业务规则和最小权限预期。',
    },
    {
      id: 'finding-003',
      title: '缺少安全响应头候选',
      severity: 'info',
      source: 'Juice Shop · 响应头',
      state: '已驳回',
      summary: '训练环境的响应头与基线存在差异，暂不作为漏洞提交。',
      evidence: '仅保存响应头名称集合，敏感值已脱敏。',
      prerequisites: ['本地 Juice Shop', '公开首页'],
      impact: '用于加固建议，不自动生成补天提交。',
    },
  ],
  reports: [
    {
      id: 'report-juice',
      name: 'juice-shop-summary.json',
      relativePath: 'reports/local/juice-shop-summary.json',
      sizeBytes: 1842,
      content: '{\n  "mode": "local-fixture",\n  "target": "127.0.0.1:3000",\n  "candidates": 2,\n  "redacted": true\n}',
      redacted: true,
    },
    {
      id: 'report-dvwa',
      name: 'dvwa-adjudication.md',
      relativePath: 'reports/local/dvwa-adjudication.md',
      sizeBytes: 2360,
      content: '# DVWA 本地候选研判\n\n该文件只供人工复核，不代表漏洞已确认。\n\n- 网络接触：仅回环\n- 证据：已脱敏\n- 提交：必须人工完成\n',
      redacted: true,
    },
    {
      id: 'report-business-api',
      name: 'business-api-object-diff.json',
      relativePath: 'reports/local/business-api-object-diff.json',
      sizeBytes: 1298,
      content: '{\n  "fixture": "business-api",\n  "comparison": "synthetic-role-a-vs-role-b",\n  "network": "loopback-only",\n  "redacted": true\n}',
      redacted: true,
    },
  ],
}
