import { test, expect } from '@playwright/test'

test('real API saves draft across reload and renders actual offline review and report files', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await expect(page).toHaveTitle('SRC-Auto 安全测试控制台')
  await page.getByRole('button', { name: '目标与授权', exact: true }).click()
  await page.getByLabel('项目名称').fill('持久化验收项目')
  await page.getByLabel('目标 URL').fill('https://example.com/app')
  await page.getByLabel('允许主机名').fill('example.com')
  await page.getByLabel('允许端口').fill('443')
  await page.getByLabel('开始时间').fill('2026-09-12T09:00')
  await page.getByLabel('结束时间').fill('2026-09-12T18:00')
  await page.getByLabel('授权证明或规则说明').fill('本地表单验收，不授权联网')
  await page.getByRole('button', { name: '保存授权草稿' }).click()
  await expect(page.getByText('授权草稿已保存', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '目标与授权', exact: true }).click()
  const selector = page.getByLabel('选择已保存草稿')
  await expect(selector.locator('option')).toHaveCount(2)
  await selector.selectOption({ index: 1 })
  await expect(page.getByLabel('项目名称')).toHaveValue('持久化验收项目')
  await page.getByRole('button', { name: '离线审阅', exact: true }).click()
  await expect(page.getByText('草稿待确认', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '候选与报告', exact: true }).click()
  await page.getByRole('button', { name: '查看 acceptance.md' }).click()
  await expect(page.getByLabel('报告内容：acceptance.md')).toContainText('真实文件内容')
  await expect(page.getByLabel('报告内容：acceptance.md')).not.toContainText('dummy-secret')
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true })
  await page.getByRole('button', { name: '系统设置', exact: true }).click()
  await expect(page.getByRole('heading', { name: '云端 AI 设置' })).toBeVisible()
  await expect(page.getByText('DeepSeek V4.1 Flash', { exact: true }).first()).toBeVisible()
  await page.getByLabel('API 密钥').fill('synthetic-e2e-key')
  await page.getByRole('button', { name: '保存设置' }).click()
  await expect(page.getByText('设置已加密保存。保存过程没有联网，也没有启用后台调用。')).toBeVisible()
  await expect(page.getByLabel('API 密钥')).toHaveValue('')
  await expect(page.getByText('已保存加密密钥')).toBeVisible()
  await page.screenshot({ path: 'test-results/ai-settings-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/workspace-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.goto('/?page=settings')
  await expect(page.getByRole('heading', { name: '云端 AI 设置' })).toBeVisible()
  expect(errors).toEqual([])
})
